version: '3.8'

services:
  email-service:
    build: ./app
    expose:
      - "3000"
    environment:
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - API_KEY=${API_KEY}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - email-service
    restart: unless-stopped
